### ISSUE TITLE
"Something went wrong" toast gets displayed when closing app via the Recents menu

### ISSUE THREAD

**Issue by Nitroretro** [wesaphzt/privatelock#13]
**Version:** 1.1 from F-Droid
**Android**: 7.1.1 armv7l
**Video:** https://i.imgur.com/Bc1ZYka.mp4

The locking function doesn't work anymore after this. It does work if you don't close it via the Recents menu. I find this to be a bug since I would assume it should just keep working in the background, right? The notification is still there though.

Thanks for this app :)

https://github.com/wesaphzt/privatelock/blob/248a8eeb0b3b8deabe98cae1c24d457e22f0bbdb/app/src/main/java/com/wesaphzt/privatelock/service/LockService.java#L181

**Comment by wesaphzt** [comment]
Thanks for raising. I can replicate the issue, seems to affect < Android 8.0.
Looks like it's due to the changes I made to to the service to reduce duplicated code, which is strange because looking at it I don't see any reason why it shouldn't work, even on older versions of Android. Maybe something to do with the backwards compatibility library.
Please downgrade to 1.0 in the meantime. Or just don't clear the recent list ;)

**Comment by wesaphzt** [comment]
I think I've fixed it.
I'll do some more testing and push an update if all's good.

**Comment by wesaphzt** [comment]
https://github.com/wesaphzt/privatelock/commit/6b560beac82e25f436f1e8f8b98ef1badfad9ce5
I'll make the 1.2 release.

**Comment by ghost** [comment]
Thanks for fixing it. Got the 1.2 update from F-Droid. It works now, but it does take some time to get going. I was wondering why this was the case, so I looked a little more into it:

From logcat:
```
09-30 00:20:10.397  3341 11810 W ActivityManager: Canceling start item Intent { act=ACTION_START_FOREGROUND_SERVICE cmp=com.wesaphzt.privatelock/.service.LockService launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } } in service ComponentInfo{com.wesaphzt.privatelock/com.wesaphzt.privatelock.service.LockService}
09-30 00:20:10.398  3341 11810 W ActivityManager: Scheduling restart of crashed service com.wesaphzt.privatelock/.service.LockService in 61062ms
```

I assume this is because of the `START_REDELIVER_INTENT`, but I don't know that much about Android development.
