### ISSUE TITLE
Does nothing, won't uninstall

### ISSUE THREAD

**Issue by RClarkKinstler** [wesaphzt/privatelock#23]
This app doesn't explain what it does, just claims that the phone will "lock" if it is stolen.  It seems to read the accelerometer but what that has to do with deciding that it had been stolen I have no idea.
Worse, it cannot be uninstalled. F-Droid reports an "unknown error" and Android settings is incapable of initiating uninstall of this app.  My first zombie app, gunking up my phone.  (Private location didn't work either, but at least it uninstalled.)

**Comment by beerisgood** [comment]
You find the explanation on https://github.com/wesaphzt/privatelock and in F-Droid: https://f-droid.org/packages/com.wesaphzt.privatelock/

> A simple app to automatically lock your phone based on movement force, or the acceleration to be more accurate.
Private Lock can help protect your privacy and security by monitoring the accelerometer in the background and if the threshold is breached, lock the screen.
The main use cases are if your phone is taken while you're using it, or you drop your phone.
As an additional bonus, it can also help save wear and tear on your power button!

**Comment by wesaphzt** [comment]
It's stated exactly what the app does, nowhere does it state it will detect and 'decide' if your phone is stolen. It "CAN help protect your privacy and security", depending on how you use it. Reading and comprehending what the app actually does first would be a good start.

You might have issues on some Android versions uninstalling it because it uses device admin and, if that's still active, it may not uninstall immediately without removing the device admin first.
If that's your issue then raise that as an issue stating that instead of than skimming the description, deciding it doesn't do what you imagined it to do and raging.

**Comment by wesaphzt** [comment]
P. Location probably won't get updated for the foreseeable future because I don't have the time for it. Feel free to contribute pull requests.
In the little time I do have I've been working on this app and there will be a fairly big update coming at some point.
