### ISSUE TITLE
(feature request) allow user to choose whether to lock or lockdown the phone

### ISSUE THREAD

**Issue by giorgiga** [wesaphzt/privatelock#8]
I would like to have an option for deciding whether the phone should be locked (ie: unlockable via fingerprint) or locked down (unlockable via pin/password/pattern only).

**Comment by wesaphzt** [comment]
I'd like this as well. Unfortunately Google haven't made this possible, it will always default to PIN code etc. when locked via DevicePolicyManager unless they change it, which they probably won't as they don't consider it an issue.

It's possible if your phone is rooted, but root isn't supported (as of now at least).
There's a workaround of dimming the screen and letting it timeout in 10 seconds or so to lock the screen 'naturally' which will allow unlocking with fingerprint or whatever, but it's a pretty terrible workaround security-wise which is why it hasn't been implemented.

**Comment by OutRunKnuckles** [comment]
The WaveUp app (https://gitlab.com/juanitobananas/wave-up/tree/HEAD) has the ability to soft lock like this with the USES_POLICY_FORCE_LOCK permission. I haven't noticed much of a difference either between it and my normal power button when it is set to immediately lock the screen.

I just really want this feature and hope you would look into it.

**Comment by beerisgood** [comment]
@wesaphzt please add the soft lock option like [WaveUp](https://gitlab.com/juanitobananas/wave-up/tree/HEAD)

**Comment by mahdi1234** [comment]
Would be great to get this in since new phones come mostly with FOD (fingerprint on display) nowdays and it's quite a pain to type pin everytime. Older phones with fingerprint reader on back weren't big deal as one could have used fingerprint all the time.

**Comment by max-baz** [comment]
If someone has time to implement this, here are the relevant pieces:

- This only works on Pie and newer
- Uses accessibility services instead of device admin
- Instead of `mDPM.lockNow()` calls like [here](https://github.com/wesaphzt/privatelock/blob/0cfce130fd48c5de01bf96ba0e1103c66f7f5833/app/src/main/java/com/wesaphzt/privatelock/service/LockService.java#L256) fire an accessibility event like [here](https://gitlab.com/juanitobananas/wave-up/-/blob/master/app/src/main/java/com/jarsilio/android/waveup/service/ScreenHandler.kt#L87-99)
- Add an accessibility service like [this one](https://gitlab.com/juanitobananas/wave-up/-/blob/master/app/src/main/java/com/jarsilio/android/waveup/service/LockAccessibilityService.kt) which receives the event and calls `performGlobalAction(GLOBAL_ACTION_LOCK_SCREEN)` to lock the screen

Good luck 👍
